---
deployment:
  tasks:
    # vendor/ e public/build/ já vêm no repo - sem necessidade de composer ou npm
    - /bin/cp -R /home1/abdonc73/repositories/iagus/. /home1/abdonc73/iagus.com.br/

    # Artisan (cada linha é um shell separado - usar caminho completo)
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan optimize:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan migrate --force
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan optimize
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan storage:link --relative

    # Permissões
    - chmod -R 775 /home1/abdonc73/iagus.com.br/storage
    - chmod -R 775 /home1/abdonc73/iagus.com.br/bootstrap/cache
