---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/abdonc73/iagus.com.br

    # vendor/ e public/build/ já vêm no repo — sem necessidade de composer ou npm
    - /bin/cp -R . $DEPLOYPATH

    # Localizar PHP
    - export PHP=/opt/cpanel/ea-php83/root/usr/bin/php
    - if [ ! -f "$PHP" ]; then export PHP=$(which php); fi

    # Artisan
    - cd $DEPLOYPATH && $PHP artisan optimize:clear 2>&1
    - cd $DEPLOYPATH && $PHP artisan migrate --force 2>&1
    - cd $DEPLOYPATH && $PHP artisan optimize 2>&1
    - cd $DEPLOYPATH && $PHP artisan storage:link --relative 2>&1

    # Permissões
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
