---
deployment:
  tasks:
    # Copiar arquivos para o diretório do site (preserva .env no destino)
    - /usr/bin/rsync -a --exclude='.git' --exclude='.env' --exclude='node_modules' --exclude='storage/logs' --exclude='storage/framework/sessions' --exclude='storage/framework/cache' --exclude='storage/framework/views' --exclude='database/database.sqlite' /home1/abdonc73/repositories/iagus/ /home1/abdonc73/iagus.com.br/

    # Garantir que diretórios de storage existem
    - mkdir -p /home1/abdonc73/iagus.com.br/storage/framework/sessions
    - mkdir -p /home1/abdonc73/iagus.com.br/storage/framework/views
    - mkdir -p /home1/abdonc73/iagus.com.br/storage/framework/cache/data
    - mkdir -p /home1/abdonc73/iagus.com.br/storage/logs
    - mkdir -p /home1/abdonc73/iagus.com.br/bootstrap/cache

    # Permissões corretas (apenas storage e cache, sem find recursivo lento)
    - chmod 755 /home1/abdonc73/iagus.com.br/artisan
    - chmod -R 775 /home1/abdonc73/iagus.com.br/storage
    - chmod -R 775 /home1/abdonc73/iagus.com.br/bootstrap/cache

    # Laravel artisan (PHP 8.3 HostGator)
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan optimize:clear
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan migrate --force
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan storage:link
    - /opt/cpanel/ea-php83/root/usr/bin/php /home1/abdonc73/iagus.com.br/artisan optimize
