---
deployment:
  tasks:
    # NOTA: vendor/ é enviado via FTP pelo GitHub Actions - não reinstalar aqui

    # 1. Limpar caches antigos
    - cd /home1/abdonc73/iagus.com.br && /usr/local/bin/php artisan optimize:clear 2>&1

    # 2. Rodar migrations
    - cd /home1/abdonc73/iagus.com.br && /usr/local/bin/php artisan migrate --force 2>&1

    # 3. Cache de produção
    - cd /home1/abdonc73/iagus.com.br && /usr/local/bin/php artisan optimize 2>&1

    # 4. Criar symlink de storage
    - cd /home1/abdonc73/iagus.com.br && /usr/local/bin/php artisan storage:link --relative 2>&1

    # 5. Permissões
    - chmod -R 775 /home1/abdonc73/iagus.com.br/storage
    - chmod -R 775 /home1/abdonc73/iagus.com.br/bootstrap/cache
